src/dj/notesgroup/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include
from django_pimentech.viewsobjects import ObjectCaller

from dj.notesgroup import views

urlpatterns = patterns(
    '',
    url(r'^$', ObjectCaller(views.IndexView)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
    url(r'^workgroup/$', ObjectCaller(views.WorkGroupView)),
    url(r'^group/(?P<societe>\d+)/(?P<action>edit)/$',
        ObjectCaller(views.SocieteEditView)),
    url(r'^group/(?P<action>new)/$', ObjectCaller(views.SocieteEditView)),
    url(r'^user/(?P<_user_edit>\d+)/(?P<action>edit)/$',
        ObjectCaller(views.UserEditView)),
    url(r'^user/(?P<action>edit)/$', ObjectCaller(views.UserEditView)),
    url(r'^user/(?P<societe>\d+)/(?P<action>new)/$',
        ObjectCaller(views.UserEditView)),
    url(r'^tree/$', ObjectCaller(views.SubTreeView)),
    url(r'^treej/$', ObjectCaller(views.SubTreeJSON)),
    url(r'^tree/(?P<note>\d+)/$', ObjectCaller(views.SubTreeView)),
    url(r'^treej/(?P<note>\d+)/$', ObjectCaller(views.SubTreeJSON)),
    url(r'^jframe_list$', ObjectCaller(views.NoteListView)),
    url(r'^(?P<note>\d+)/detail_list/$', ObjectCaller(views.DetailListView)),
    url(r'^(?P<note>\d+)/(?P<action>edit|new)/$',
        ObjectCaller(views.NoteEditView)),
    url(r'^(?P<note>\d+)/add_comment/$',
        ObjectCaller(views.NoteAddCommentView)),
    url(r'^(?P<note>\d+)/detail/$', ObjectCaller(views.NoteDetailView)),
    url(r'^(?P<note>\d+)/detail_new_window/$',
        ObjectCaller(views.NoteDetailNewWindowView)),
    url(r'^(?P<note>\d+)/diff/', ObjectCaller(views.NoteDiffView)),
    url(r'^(?P<note>\d+)/users/$', ObjectCaller(views.NoteUsersView)),
    url(r'^(?P<note>\d+)/move_to/(?P<new_parent>\d+)/$',
        ObjectCaller(views.NoteMoveView)),
    url(r'^(?P<note>\d+)/clone/', ObjectCaller(views.NoteCloneView)),
    url('^attachments/(?P<path>.*)$', ObjectCaller(views.ServerAttachment), name='serve_attachements'),

    url(r'^(?P<note>\d+)/timer/(?P<timer>\d+)/',
        ObjectCaller(views.TimerEditView)),
    url(r'^(?P<note>\d+)/timer/',
        ObjectCaller(views.TimerEditView)),
    url(r'^(?P<note>\d+)/set_timer/',
        ObjectCaller(views.SetTimerView)),
    url(r'^get_timer_day/',
        ObjectCaller(views.GetTimerDayView)),



    (r'^i18n/', include('django.conf.urls.i18n')),
    # changement de password par l'utilisateur loggue
    url(r'^password_change/$', 'django.contrib.auth.views.password_change'),
    url(r'^password_change/done/$',
        'django.contrib.auth.views.password_change_done'),
    # reset du password ( si perte par ex)
    url(r'^password_reset_request/$',
        'django.contrib.auth.views.password_reset'),
    url(r'^password_reset_done/$',
        'django.contrib.auth.views.password_reset_done'),
    url(r'^password_reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm'),
    url(r'^password_reset_complete/$',
        'django.contrib.auth.views.password_reset_complete'),

    url(r'^notes$', ObjectCaller(views.NoteListJsonView)),
)

src/dj/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()


commonpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    (r'', include('dj.notesgroup.urls')),
    (r'^api/', include('dj.api.urls')),
)

if settings.DEVELOPMENT_ENVIRON:
    urlpatterns = patterns(
        '',
        (r'^static/pimentech/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.HOME + '/src/scripts/src/'}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_DIR}),
        (r'^pimentech/img/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.HOME + '/src/scripts/src/images/'}),
        (r'^pimentech/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.HOME + '/src/scripts/src/'}),
    ) + commonpatterns
else:
    urlpatterns = commonpatterns

src/dj/notesgroup/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.db.models import signals, Model, Manager, AutoField, ForeignKey, \
    CharField, IntegerField, FloatField, DateField, DateTimeField, \
    EmailField, BooleanField, FileField
from django.db import connection
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage

from entities import entities
from utils import send_mail, note_diff
import inspect

import os
import sys
import datetime
from django.utils.translation import ugettext as _


def save(instance, authenticated_user):
    if instance.authcrea is None:
        instance.authcrea = authenticated_user
    instance.authmodif = authenticated_user
    instance.save()


def _set_paths(parent):
    try:
        for note in Note.objects.filter(parent=parent):
            note.path = parent.path + '/%s' % note.uid
            note.save()
            _set_paths(note)
    except:
        pass


def set_paths():
    for note in Note.objects.filter(parent=0).exclude(uid=0):
        note.path = '/%s' % note.uid
        note.save()
        _set_paths(note)


class Object(Model):

    class Meta:
        db_table = 'object'

    uid = AutoField('ID', primary_key=True)
    authcrea = ForeignKey(User, db_column='authcrea',
                          related_name='object_authcrea', editable=False, null=True, blank=True)
    authmodif = ForeignKey(User, db_column='authmodif',
                           related_name='object_authmodif', editable=False, null=True, blank=True)
    codecrea = CharField(max_length=200, null=True, blank=True)
    codemodif = CharField(max_length=200, null=True, blank=True)
    datecrea = DateTimeField(auto_now_add=True, null=True, blank=True)
    datemodif = DateTimeField(auto_now_add=True, null=True, blank=True)
    nom = CharField(max_length=200, null=True, blank=True)
    statut = IntegerField(default=0, null=True, blank=True)


class TypeEmploye(Model):

    class Meta:
        db_table = 'type_employe'

    uid = AutoField('ID', primary_key=True)
    authcrea = ForeignKey(User, db_column='authcrea',
                          related_name='type_employe_authcrea',
                          editable=False, null=True, blank=True)
    authmodif = ForeignKey(User, db_column='authmodif',
                           related_name='type_employe_authmodif',
                           editable=False, null=True, blank=True)
    codecrea = CharField(max_length=200, null=True, blank=True)
    codemodif = CharField(max_length=200, null=True, blank=True)
    datecrea = DateTimeField(auto_now_add=True, null=True, blank=True)
    datemodif = DateTimeField(auto_now_add=True, null=True, blank=True)
    nom = CharField(max_length=200, null=True, blank=True)
    statut = IntegerField(default=0, null=True, blank=True)

    def __unicode__(self):
        return self.nom


class Personne(Model):

    class Meta:
        db_table = 'personne'

    uid = AutoField('ID', primary_key=True)
    authcrea = ForeignKey(User, db_column='authcrea',
                          related_name='personne_authcrea', editable=False,
                          null=True, blank=True)
    authmodif = ForeignKey(User, db_column='authmodif',
                           related_name='personne_authmodif', editable=False,
                           null=True, blank=True)
    codecrea = CharField(max_length=200, null=True, blank=True)
    codemodif = CharField(max_length=200, null=True, blank=True)
    datecrea = DateTimeField(auto_now_add=True, null=True, blank=True)
    datemodif = DateTimeField(auto_now_add=True, null=True, blank=True)
    nom = CharField(max_length=200, null=True, blank=True)
    statut = IntegerField(default=0, null=True, blank=True)
    adresse1 = CharField(max_length=200, null=True, blank=True)
    adresse2 = CharField(max_length=200, null=True, blank=True)
    commentaire = CharField(max_length=200, null=True, blank=True)
    cp = CharField(max_length=200, null=True, blank=True)
    email = CharField(max_length=200, null=True, blank=True, unique=True)
    euid = CharField(max_length=200, null=True, blank=True)
    fax = CharField(max_length=200, null=True, blank=True)
    pays = CharField(max_length=200, null=True, blank=True)
    tel = CharField(max_length=200, null=True, blank=True)
    tel2 = CharField(max_length=200, null=True, blank=True)
    ville = CharField(max_length=200, null=True, blank=True)
    web = CharField(max_length=200, null=True, blank=True)


class Societe(Model):

    class Meta:
        db_table = 'societe'

    uid = AutoField('ID', primary_key=True)
    statut = IntegerField(default=0, null=True, blank=True)
    authcrea = ForeignKey(User, db_column='authcrea',
                          related_name='societe_authcrea',
                          null=True, blank=True)
    authmodif = ForeignKey(User, db_column='authmodif',
                           related_name='societe_authmodif',
                           null=True, blank=True)
    codecrea = CharField(max_length=200, null=True, blank=True)
    codemodif = CharField(max_length=200, null=True, blank=True)
    datecrea = DateTimeField(auto_now_add=True, null=True, blank=True)
    datemodif = DateTimeField(auto_now_add=True, null=True, blank=True)

    nom = CharField(max_length=200, null=True, blank=True, unique=True)
    adresse1 = CharField(max_length=200, null=True, blank=True)
    adresse2 = CharField(max_length=200, null=True, blank=True)
    cp = CharField(max_length=200, null=True, blank=True)
    ville = CharField(max_length=200, null=True, blank=True)
    pays = CharField(max_length=200, null=True, blank=True)

    email = EmailField(max_length=200, null=True, blank=True)

    commentaire = CharField(max_length=200, null=True, blank=True)
    euid = CharField(max_length=200, null=True, blank=True)
    fax = CharField(max_length=200, null=True, blank=True)
    tel = CharField(max_length=200, null=True, blank=True)
    tel2 = CharField(max_length=200, null=True, blank=True)
    web = CharField(max_length=200, null=True, blank=True)
    logo = CharField(max_length=200, null=True, blank=True)
    raison = CharField(max_length=200, null=True, blank=True)
    siren = CharField(max_length=200, null=True, blank=True)
    siret = CharField(max_length=200, null=True, blank=True)
    ue_tva = CharField(max_length=200, null=True, blank=True)

    def __unicode__(self):
        return self.nom


class PersonnePhysique(Model):

    class Meta:
        db_table = 'personne_physique'

    uid = AutoField('ID', primary_key=True)
    authcrea = ForeignKey(User, db_column='authcrea',
                          related_name='personne_physique_authcrea',
                          editable=False, null=True, blank=True)
    authmodif = ForeignKey(User, db_column='authmodif',
                           related_name='personne_physique_authmodif',
                           editable=False, null=True, blank=True)
    codecrea = CharField(max_length=200, null=True, blank=True)
    codemodif = CharField(max_length=200, null=True, blank=True)
    datecrea = DateTimeField(auto_now_add=True, null=True, blank=True)
    datemodif = DateTimeField(auto_now_add=True, null=True, blank=True)
    nom = CharField(max_length=200, null=True, blank=True)
    statut = IntegerField(default=0, null=True, blank=True)
    adresse1 = CharField(max_length=200, null=True, blank=True)
    adresse2 = CharField(max_length=200, null=True, blank=True)
    commentaire = CharField(max_length=200, null=True, blank=True)
    cp = CharField(max_length=200, null=True, blank=True)
    email = CharField(max_length=200, null=True, blank=True)
    euid = CharField(max_length=200, null=True, blank=True)
    fax = CharField(max_length=200, null=True, blank=True)
    pays = CharField(max_length=200, null=True, blank=True)
    tel = CharField(max_length=200, null=True, blank=True)
    tel2 = CharField(max_length=200, null=True, blank=True)
    ville = CharField(max_length=200, null=True, blank=True)
    web = CharField(max_length=200, null=True, blank=True)
    administrateur = IntegerField(default=0, null=True, blank=True)
    civilite = IntegerField(null=True, blank=True)
    key = CharField(max_length=200, null=True, blank=True)
    naissance = DateField(null=True, blank=True)
    prenom = CharField(max_length=200, null=True, blank=True)


class Employe(Model):

    class Meta:
        db_table = 'employe'

    user = ForeignKey(User, unique=True)

    uid = AutoField('ID', primary_key=True)
    authcrea = ForeignKey(User, db_column='authcrea',
                          related_name='employe_authcrea', editable=False,
                          null=True, blank=True)
    authmodif = ForeignKey(User, db_column='authmodif',
                           related_name='employe_authmodif', editable=False,
                           null=True, blank=True)
    codecrea = CharField(max_length=200, null=True, blank=True)
    codemodif = CharField(max_length=200, null=True, blank=True)
    datecrea = DateTimeField(auto_now_add=True, null=True, blank=True)
    datemodif = DateTimeField(auto_now_add=True, null=True, blank=True)
    nom = CharField(max_length=200, null=True, blank=True)
    statut = IntegerField(default=0, null=True, blank=True)
    adresse1 = CharField(max_length=200, null=True, blank=True)
    adresse2 = CharField(max_length=200, null=True, blank=True)
    commentaire = CharField(max_length=200, null=True, blank=True)
    cp = CharField(max_length=200, null=True, blank=True)
    email = CharField(max_length=200, null=True, blank=True, unique=True)
    euid = CharField(max_length=200, null=True, blank=True)
    fax = CharField(max_length=200, null=True, blank=True)
    pays = CharField(max_length=200, null=True, blank=True)
    tel = CharField(max_length=200, null=True, blank=True)
    tel2 = CharField(max_length=200, null=True, blank=True)
    ville = CharField(max_length=200, null=True, blank=True)

src/dj/templates/notesgroup/base.html
{% load i18n %}
{% load url from future %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="shortcut icon" type="image/x-icon" href="{{ http_static }}/img/favicon.ico" />
        {% if debug %}
            <link href="{{ http_static }}/css/intra.css" rel="stylesheet" type="text/css" />
            <link href="{{ http_static }}/css/jquery-ui.custom.css" rel="stylesheet" type="text/css" />
            <script type="text/javascript" src="/pimentech/js/jquery.js"></script>
            <script type="text/javascript" src="/pimentech/js/jquery-ui.js"> </script>
            <script type="text/javascript" src="{{ http_static }}/js/jquery.tooltip.js"> </script>
            <script type="text/javascript" src="/pimentech/js/jquery.form.js"></script>
            <script type="text/javascript" src="/pimentech/js/jquery.jframe.js"></script>
            <script type="text/javascript" src="{{http_static}}/pimentech/lib/tiny_mce/jquery.tinymce.js"></script>
            <script type="text/javascript" src="/pimentech/js/jquery.treeview.pack.js"> </script>
            <script type="text/javascript" src="{{ http_static }}/js/jquery.dj.js"> </script>
        {% else %}
            <link href="{{ http_static }}/css/notesgroup.min.css" rel="stylesheet" type="text/css" />
            <script type="text/javascript" src="{{ http_static }}/js/lib.min.js"></script>
        {% endif %}
        <script type="text/javascript">
         <!--
         var http_static = '{{ http_static}}';
         img_plus = new Image();
         img_plus.src = '{{ http_static }}/img/list-add.png';
         img_moins = new Image();
         img_moins.src = '{{ http_static }}/img/list-remove.png';
         var utilisateur_authentifie = '{{ user.username }}';
         var employe_dict = { {% for e in employe.workgroup %}{{ e.uid }}:{'name':'{{ e.prenom }} {{ e.nom }}','tel':'{{ e.tel }}'}{% if not forloop.last %},{% endif %}{% endfor %} };
         $(document).ready(function() {
           resizeNotesGroup();
           $("#id_date_start").datepicker();
           $("#id_date_end").datepicker();
           {% if note_src %}
           $("#detail_list_container_{{ note_src }}").fadeIn().loadJFrame("/{{ note_src }}/detail/");
           {% endif %}
           $("button, input:submit").button();
           $('span.detail_list').live("click", function() { var uid = this.id; uid=uid.split('_')[2];showHideDetail(this, uid); });
           $("#form_search").find("select,input").bind("change", highlightInput);
         });
         -->
        </script>
        <style type="text/css">
        </style>
        {% block extra_head %}
        {% endblock %}
        <title>NotesGroup</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

src/dj/templates/notesgroup/edit_form.html
{% load i18n %}
<script>
  NOW = '{% now "r" %}';
</script>
<form action="{{ path }}" method="post">
<table>
  {{ form.as_table }}
  <tr>
    <td colspan="2">
      <input type="submit" value="{% trans "Save" %}"/>
    </td>
</table>
</form>

src/dj/templates/notesgroup/go_search.html
<script type="text/javascript">
goSearch('{{ uid }}');
</script>

src/dj/templates/notesgroup/index2.html
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NotesGroup</title>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/fontawesome/4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/g/bootstrap@3.1(css/bootstrap.min.css+css/bootstrap-theme.min.css)">

    <link rel="stylesheet" href="{{ http_static }}/css/tree-control.css"></script>
    <link rel="stylesheet" href="{{ http_static }}/css/notesgroup.css"></script>

    <script src="//cdn.jsdelivr.net/g/angularjs@1.2(angular.min.js+angular-animate.min.js+angular-cookies.min.js+angular-route.min.js+angular-sanitize.min.js)"></script>
    <script src='//cdn.jsdelivr.net/g/angular.textangular@1.2(textAngular-sanitize.min.js+textAngular.min.js)'></script>

    <script>
     var DEBUG = true;
     var USERID = {{ user.id }};
     var EMP_L = {{ employe_l|safe }};
    </script>
    <script src="{{ http_static }}/js/ext/angular-tree-control.js"></script>
    <script src="{{ http_static }}/js/app.js"></script>
    <script src="{{ http_static }}/js/controllers.js"></script>
  </head>
  <body ng-app="myApp" ng-controller="TopCtrl" ng-init="initialize()">
    <div class="container" ng-controller="NoteCtrl" ng-init="initialize()">
      <div class="row">
        <div class="col-md-2">
          <a href="" ng-click="goTodo()">
            <i class="fa fa-check-circle-o fa-4x" title="{% trans "What I have to do." %}"></i>
          </a>
          <a href="" ng-click="goAsked()">
            <i class="fa fa-question fa-4x" title="{% trans "What I have asked (From:me, state:open)" %}"></i>
          </a>
        </div>
        <div class="col-md-10">

          <form class="form-inline" role="form">
            <label>
              {% trans "State" %}
              {{ form.etat_note }}
            </label>
            <label>
              {% trans "Scope" %}
              {{ form.path }}
              <span id="html_chemin_txt"></span>
            </label>
            <label>
              {% trans "From" %}
              <select ng-model="queryParams.demandeur" ng-options="e.uid as e.title group by e.societe for e in emp_l"></select>
            </label>
            <label>
              {% trans "To" %}
              <select ng-model="queryParams.responsable" ng-options="e.uid as e.title group by e.societe for e in emp_l"></select>
            </label>
            <label>
              <b>{% trans "Actor" %}</b>&nbsp;
              <select ng-model="queryParams.timer_actor" ng-options="e.uid as e.title group by e.societe for e in emp_l"></select>
              <input type="text" ng-model="queryParams.timer_date" />
            </label>
            <label>
              <b>{{ form.sel_txt }}</b>
            </label>
            <label>
              {% trans "contains" %} <input type="text" id="id_resume" name="txt" size="40" />
            </label>

            <span id="label_group">
              {% trans "Modified between" %} <input type="text" ng-model="queryParams.date_start" />
              {% trans "and" %} <input type="text" ng-model="queryParams.date_start" />
            </span>
            <input type="hidden" id="id_chemin" name="chemin" />

            <label>
              {{ form.limit }} {% trans "results" %}
            </label>

            <input class="btn btn-primary" type="submit" value="{% trans "Search" %}" ng-click="load()" />

          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          {% verbatim %}
            <treecontrol tree-model="top.tree"
                         options="treeOptions"
                         on-selection="showSelected(node)"
                         selected-node="node1">
              <i class="fa fa-{{ icon[node.type_note] }}"></i> {{node.nom}}
            </treecontrol>
          {% endverbatim %}
        </div>
        <div class="col-md-10">
          <div class="list-group">
            <div ng-repeat="note in top.notes" class="list-group-item">
              {% verbatim %}
                <h4 class="list-group-item-headings"><i class="fa fa-{{ icon[note.type_note] }}"></i><a href="" ng-click="toggleDetail(note)">{{ note.nom }}</a><small>{{ note.resume }}</small></h4>
              {% endverbatim %}
              <p class="list-group-item-text">
                <form role="form" class="form-inline" ng-show="note.showDetail">
                  <div class="form-group">
                    <label>{% trans "Name" %}</label>
                    {% verbatim %}{% endverbatim %}

                    <input type="text" class="form-control" ng-model="note.nom" />
                  </div>
                  <div class="form-group">
                    <label>{% trans "Type" %}</label>
                    <select class="form-control" ng-model="note.type_note" ng-options="e.id as e.name for e in [
                            {id:0, name:'indefini'},
                            {id:1, name:'département'},
                            {id:2, name:'dossier'},
                            {id:3, name:'projet'},
                            {id:4, name:'tâche'},
                            {id:5, name:'rendez-vous'},
                            {id:6, name:'bug'},
                            {id:7, name:'souhait'},
                            {id:8, name:'message'}
                            ]"></select>
                  </div>
                  <div class="form-group">
                    <label>{% trans "State" %}</label>
                    <select class="form-control" ng-model="note.etat_note" ng-options="e.id as e.name for e in [
                            {id:0, name:'{% trans "undefined" %}'},
                            {id:1, name:'{% trans "open" %}'},
                            {id:2, name:'{% trans "pending" %}'},
                            {id:3, name:'{% trans "resolved" %}'},
                            {id:4, name:'{% trans "cancelled" %}'}
                            ]"></select>
                  </div>
                  <div class="form-group">
                    <label>{% trans "Summary" %}</label>
                    <div class="col-xs-4">
                      <input type="text" class="form-control" ng-model="note.resume" />
                    </div>
                  </div>
                  <div class="form-group">
                    <label>{% trans "From" %}</label>
                    <select class="form-control" ng-model="note.demandeur_employe" ng-options="e as emp_d[e].title for e in note.actors"></select>
                  </div>
                  <div class="form-group">
                    <label>{% trans "To" %}</label>
                    <select class="form-control" ng-model="note.responsable_employe" ng-options="e as emp_d[e].title for e in note.actors"></select>
                  </div>
                  <div ng-show="note.showDetail" text-angular ng-model="note.description"></div>

                  <input class="btn btn-primary" type="submit" ng-click="save(note)" />
                </form>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

src/dj/templates/notesgroup/note_detail_new_window.html
{% extends "notesgroup/base.html" %}
{% load i18n %}

{% block extra_head %}
<style type="text/css">
  body { overflow:auto; }
</style>
{% endblock %}
{% block content %}
<span style="background-color:#DDD;width:100%">
  {% call "module_note_detail_list" note %}
</span>
<div class="box">
  {{ note.description|safe }}
</div>

{% if note.attachments %}
<h3>{% trans "Attached files" %}</h3>
<ul>
{% for attachment in note.attachments %}
<li><a href="{{ attachment.source }}" target="_blank">{{ attachment.source }}</a></li>
{% endfor %}
<ul>
{% endif %}
<div id="detail_note_comment_{{ note.pk }}"></div>

<script type="text/javascript">
  $(document).ready(function() {
    //$("a.button").button();
    //selectTreeCellParent('{{ note.path }}');
    usersStr();
    $("#detail_list_container_{{ note }} .box a").attr("target","_blank");
    window.print();
  });
</script>
{% endblock %}

src/dj/templates/notesgroup/note_list.html
{% load i18n %}
<div id="top-list-id" class="top-list" >
    {% with form.cleaned_data as clean %}
        {% if parent_note and parent_note.pk and parent_note.description|striptags %}
            {{ parent_note.description|safe }}
        {% endif %}

        {% ifequal clean.path "ici" %}
            <button onclick="newNote({{ parent_note.pk }})">{% trans "Add note" %}</button>
            {% trans "in" %} <span id="human_path_{{ parent_note.pk }}"></span>
            <script type="text/javascript">
             $("#human_path_{{ parent_note.pk }}").html(humanPathFromTree({{ parent_note.pk }}));
             $("button, input:submit").button();
            </script>
        {% else %}
            {% trans "Scope : everywhere" %}
        {% endifequal %}

        {% if clean.demandeur %}
            {% trans "From" %} : <user>{{ clean.demandeur }}</user>
        {% endif %}

        {% if clean.responsable %}
            {% trans "To" %} : <user>{{ clean.responsable }}</user>
        {% endif %}
    {% endwith %}

</div>
{{ form.errors }}

{% if notes.object_list %}
    <div id="pagination-id" class="pagination">
        <span class="step-links">
            {% if notes.has_previous %}
                <a href="javascript:goPage({{ notes.previous_page_number }})">
                    {% trans "previous notes" %}
                </a>
            {% endif %}

            <span class="current">
                {{ notes.paginator.count }} {% trans "results" %},
                {% trans "page" %}
                {{ notes.number }}/{{ notes.paginator.num_pages }}.
                {{ duration|floatformat:2 }}h
                {{ duration_in_days|floatformat:2 }}d
                {% if timer_duration %}
                    <span class="ui-widget-header">{{ timer_date }} : {{ timer_duration }} {% trans "hours" %}  </span>
                {% endif %}
            </span>

            {% if notes.has_next %}
                <a href="javascript:goPage({{ notes.next_page_number }})">{% trans "next notes" %}</a>
            {% endif %}
        </span>
    </div>

    <div id="notes-list-id">
        {% for note in notes.object_list %}
            <div id="detail_list_container_{{ note.uid }}"
                 class="note-list" src="#">
                {% call "module_note_detail_list" note %}
            </div>
        {% endfor %}
        {{ note_name }}
    </div>
    <br />

{% else %}
    <div id="no-result-id">{% trans "No result" %}</div>
    <div id="notes-list-id"/>
{% endif %}